/**
 * Local Node server is no longer used for AI image generation.
 * Memory Moments distractors are generated by the Cloudflare Worker:
 * https://memory-moments-ai.rero0042006.workers.dev/
 *
 * This process only exposes a health check so local tooling can still
 * verify that something is listening if needed.
 */
import express from "express";

const PORT = Number.parseInt(process.env.PORT ?? "3000", 10);
const app = express();
app.disable("x-powered-by");

app.get("/health", (_req, res) => {
  res.json({
    ok: true,
    imageGeneration: "cloudflare-worker",
    workerUrl: "https://memory-moments-ai.rero0042006.workers.dev/"
  });
});

app.use((_req, res) => {
  res.status(410).json({
    success: false,
    error: "Local Gemini image generation was removed. Use the Cloudflare Worker."
  });
});

app.listen(PORT, "0.0.0.0", () => {
  console.info(`Memory Moments health server on ${PORT} (AI via Cloudflare Worker)`);
});
